---
driver:
  name: docker

driver_config:
  use_sudo: false
  # because Docker and SystemD/Upstart
  privileged: true
  remove_images: false
  hostname: <%= ENV.fetch('INSTANCE_NAME', "jenkins-demo") %>
  # tls_verify: true
  # tls_cacert: <%= ENV.fetch('TLS_FOLDER', "tls") %>/ca.pem
  # tls_cert: <%= ENV.fetch('TLS_FOLDER', "tls") %>/cert.pem
  # tls_key: <%= ENV.fetch('TLS_FOLDER', "tls") %>/key.pem
  # socket: tcp://172.17.0.1:4243
transport:
   username: kitchen

provisioner:
  name: chef_zero
  require_chef_omnibus: 13.6.4
  data_path: test/shared
  client_rb:
      file_cache_path: "/var/chef/cache"

platforms:
  - name: centos-7
    driver_config:
      # https://hub.docker.com/r/dokken/centos-7/
      instance_name: <%= ENV.fetch('INSTANCE_NAME', "jenkins-demo-centos7") %>
      image: <%= ENV.fetch('IMAGE_NAME', "dokken/centos-7") %>
      pid_one_command: /usr/lib/systemd/systemd
      forward:
        - <%= ENV.fetch('DOCKER_PORT_FORWARD_PREFIX', "180") %>83:8081
  - name: ubuntu-14.04
    driver_config:
      instance_name: <%= ENV.fetch('INSTANCE_NAME', "jenkins-demo-ubuntu1404") %>
      image: <%= ENV.fetch('IMAGE_NAME', "ubuntu:14.04") %>
      forward:
        - <%= ENV.fetch('DOCKER_PORT_FORWARD_PREFIX', "280") %>83:8081

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[jenkins-demo::default]
      - recipe[jenkins-demo::conf_test_job]
    attributes:
        {jenkins_demo:
                {jenkins_port: '8081',
                slack_teamdomain: 'mywechat',
                slack_authtoken: '<%= ENV.fetch('SLACK_TOKEN', "") %>',
                # TODO different env use different port
                # TODO use server ip
                slack_buildserverurl: 'http://localhost:<%= ENV.fetch('DOCKER_PORT_FORWARD_PREFIX', "180") %>80/',
                slack_room: '#denny-alerts',
                default_username: '<%= ENV.fetch('JENKINS_DEFAULT_USERNAME', "usertest123") %>',
                default_password: '<%= ENV.fetch('JENKINS_DEFAULT_PASSWORD', "password123") %>'
                }
        }
